package warhammerrpg.gui.network;

import warhammerrpg.GameMechanics.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;


public class MasterGuiForm {


    public MasterGuiForm() {
        throwDice.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                Dice kostka = new Dice();
                if (twoDices.isSelected()) {
                    diceResult.setText(kostka.twoDicesThrow().toString());
                } else {
                    diceResult.setText(kostka.oneDiceThrow().toString());
                }

            }
        });
        twoDices.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                oneDice.setSelected(Boolean.FALSE);
                twoDices.setSelected(Boolean.TRUE);
            }
        });
        oneDice.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                oneDice.setSelected(Boolean.TRUE);
                twoDices.setSelected(Boolean.FALSE);
            }
        });
    }

    public JPanel getPanel() {
        return panel;
    }

    private JPanel panel;
    private JTextArea message;
    private JButton throwDice;
    private JTextField diceResult;
    private JRadioButton oneDice;
    private JRadioButton twoDices;
    private JRadioButton twoDice;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */

}

