CREATE TABLE SKILL (
	ID                   INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	NAME                 VARCHAR(255) NOT NULL,
	DESCRIPTION          TEXT,
	ISADVANCED           TINYINT,
	RELATEDTALENTSSTRING VARCHAR(255),
	CHARACTERISTIC       VARCHAR(255)
)
;

CREATE UNIQUE INDEX SKILL_NAME_IDX
	ON SKILL (NAME)
;

CREATE TABLE PERSON (
	ID                INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	NAME              VARCHAR(255),
	BREED             VARCHAR(255),
	CURCAREER_ID      INTEGER,
	PREVCAREER_ID     INTEGER,
	AGE               VARCHAR(255),
	EYESCOLOUR        VARCHAR(255),
	HAIRCOLOUR        VARCHAR(255),
	STARSIGN          VARCHAR(255),
	SEX               VARCHAR(255),
	WEIGHT            VARCHAR(255),
	HEIGHT            VARCHAR(255),
	SIBLINGS          VARCHAR(255),
	BIRTHPLACE        VARCHAR(255),
	SPECIALSIGNS      VARCHAR(255),
	WEAPONSKILL_ID    INTEGER,
	BALLISTICSKILL_ID INTEGER,
	STRENGTH_ID       INTEGER,
	TOUGHNESS_ID      INTEGER,
	AGILITY_ID        INTEGER,
	INTELLIGENCE      INTEGER,
	WILLPOWER_ID      INTEGER,
	FELLOWSHIP_ID     INTEGER,
	ATTACK_ID         INTEGER,
	WOUNDS_ID         INTEGER,
	STRENGTHBONUS_ID  INTEGER,
	TOUGHNESSBONUS_ID INTEGER,
	MOVEMENT_ID       INTEGER,
	MAGIC_ID          INTEGER,
	INSANITYPOINTS_ID INTEGER,
	FATEPOINTS_ID     INTEGER,
	GAMERNAME         VARCHAR(255),
	GAMENASTER        VARCHAR(255),
	CAMPAIGN          VARCHAR(255),
	CAMPAIGNYEAR      INTEGER,
	CUREXP            VARCHAR(255),
	ALLEXP            VARCHAR(255),
	MOVE              INTEGER,
	ATTACKRUN         INTEGER,
	RUN               INTEGER,
	HEAD              INTEGER,
	BODY              INTEGER,
	RIGHTHAND         INTEGER,
	LEFTHAND          INTEGER,
	RIGHTLEG          INTEGER,
	LEFTLEG           INTEGER,
	GOLD              VARCHAR(255),
	SILVER            VARCHAR(255),
	BRASS             VARCHAR(255)
)
;

CREATE TABLE PERSONTOSKILL (
	ID         INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	PERSON_ID  INTEGER,
	SKILL_ID   INTEGER,
	PLUSTEN    TINYINT,
	PLUSTWENTY TINYINT
)
;

CREATE TABLE WEAPON (
	ID             INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	NAME           VARCHAR(255) NOT NULL,
	LOAD           INTEGER,
	CATEGORY       VARCHAR(100),
	DAMAGE         INTEGER,
	RANGE          INTEGER,
	RELOADTIME     INTEGER,
	WEAPONFEATURES VARCHAR(255)
)
;

CREATE UNIQUE INDEX WEAPON_NAME_IDX
	ON WEAPON (NAME)
;

CREATE TABLE PERSONTOWEAPON (
	ID        INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	PERSON_ID INTEGER,
	WEAPON_ID INTEGER
)
;

CREATE TABLE EQUIPMENT (
	ID               INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	ITEM             VARCHAR(255),
	EQUIPLOAD        VARCHAR(255),
	EQUIPDESCRIPTION VARCHAR(255),
	PERSON_ID        INTEGER
)
;

CREATE TABLE TALENT (
	ID          INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	NAME        VARCHAR(255),
	DESCRIPTION TEXT
)
;

CREATE TABLE CAREER (
	ID             INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	NAME           VARCHAR(255),
	DESCRIPTION    TEXT,
	WEAPONSKILL    INTEGER,
	BALLISTICSKILL INTEGER,
	STRENGTH       INTEGER,
	TOUGHNESS      INTEGER,
	AGILITY        INTEGER,
	INTELLIGENCE   INTEGER,
	WILLPOWER      INTEGER,
	FELLOWSHIP     INTEGER,
	ATTACK         INTEGER,
	WOUNDS         INTEGER,
	STRENGTHBONUS  INTEGER,
	TOUGHNESSBONUS INTEGER,
	MOVEMENT       INTEGER,
	MAGIC          INTEGER,
	INSANITYPOINTS INTEGER,
	FATEPOINTS     INTEGER,
	AVAIBLESKILLS  TEXT,
	AVAIBLETALENTS TEXT,
	EQUIPMENTS     TEXT,
	ISADVANCED     TINYINT
)
;

CREATE TABLE CAREEREXIT (
	ID            INTEGER AUTO_INCREMENT
		PRIMARY KEY,
	CAREER_ID     INTEGER,
	CAREEREXIT_ID INTEGER
)
;

