INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     1,'Brzuchomówstwo','Bohater potrafi mówić bez otwierania ust. Osoby uważnie obserwujące Bohatera korzystającego z tej umiejętności mogą wykonać test spostrzegawczości przeciwko testowi brzuchomówstwa BG, żeby wykryć sztuczkę Bohatera.',1,'','ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     2,'Charakteryzacja','Wykorzystanie tej umiejętności pozwała Bohaterowi maskować jego prawdziwy wygląd i udawać kogoś innego.
Często potrzebne są dodatkowe rekwizyty, właściwe ubranie łub peruka. Dzięki tej umiejętności Bohater może przebrać się za przedstawiciela innej rasy, osobę płci przeciwnej, a nawet kogoś sławnego i znanego w całym kraju, choć tego rodzaju charakteryzacja jest znacznie trudniejsza.
Przeciwko charakteryzacji często wykorzystuje się test
spostrzegawczości przeciwnika.',NULL,'naśladowca','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     3,'Czytanie i pisanie','Bohater potrafi czytać i pisać w dowolnym języku, którym umie się posługiwać. W większości przypadków czytania i pisania nic trzeba testować. Mistrz Gry może jednak zdecydować, że test umiejętności jest potrzebny przy odcyfrowywaniu rękopisu spisanego w starożytnym języku, lub zawierającym niezrozumiałe wyrażenia albo archaiczne słownictwo',1,'poliglota','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     4,'Czytanie z warg','Dzięki tej umiejętności Bohater może zrozumieć rozmowy prowadzone poza zasięgiem jego słuchu lub gdy rozmowa jest zagłuszana przez jakieś odgłosy. Musi widzieć usta obserwowanej osoby, jak również znać język, w którym prowadzona jest rozmowa.',1,'bystry wzrok','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     5,'Dowodzenie','Korzystający z tej umiejętności Bohater cieszy się posłuchem u podwładnych. Po udanym teście umiejętności podwładni dokładnie wypełniają jego polecenia. Nieudany test powoduje, że rozkaz zostaje wypełniony błędnic lub też nic zostaje wykonany w ogóle (zależnie od decyzji Mistrza Gry). Dowodzenie nie ma wpływu na zachowanie osób postronnych, umożliwia posłuszeństwo osób podlegających władzy Bohatera.',NULL,'','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     6,'Gadanina','Bohaterowie posiadający tę umiejętność mogą próbować zagadać osobę, zasypując ją potokiem słów. Korzystający z tej umiejętności Bohater zazwyczaj nic próbuje na nikogo wpływać (do tego służy przekonywanie), chcc po prostu zyskać na czasie. Po udanym teście umiejętności gadanina ofiara ma prawo do testu Siły Woli, który określa, czy zorientowała się w tym , co się naprawdę dzieje. Nieudany test oznacza, że -zagadana" osoba nic nic robi przez całą rundę, zastanawiając się. czy ma do czynienia z osobnikiem pijanym czy zwykłym idiotą, a może jedno i drugie. Gadanina nie przynosi rezultatu, jeśli ofiara bierze udział w walce lub stoi w obliczu ewidentnego zagrożenia życia. Bohater może próbować zagadać kilka osób (jedna osoba za każde 10 punktów jego Ogłady), pod warunkiem, że wszystkie te osoby rozumieją język, którym się posługuje.',1,'','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     7,'Hazard','Umiejętność hazard zwiększa szansę Bohatera na wygraną w grach losowych, takich jak karty lub kości. Każda uczestnicząca w grze postać wpłaca stawkę, a potem wszyscy grający jednocześnie wykonują test hazardu. Najniższy wynik rzutu (oczywiście, przy udanym teście) oznacza wygranie puli.',NULL,'geniusz arytmetyczny','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     8,'Hipnoza','Używając hipnozy Bohater może wprowadzić inną osobę w trans. Uwaga hipnotyzowanej osoby musi być przez minutę skupiona na jednej rzeczy (często wykorzystuje się jakąś błyskotkę na łańcuszku lub zapaloną świecę). Potem należy wykonać test umiejętności. Osoby próbujące opierać się hipnozie mogą wykonać test Siły Woli. Po wprowadzeniu osoby w trans. Bohater może jej zadać jedno pytanie za każde 10 punktów swojej Siły Woli. Osoba udziela odpowiedzi szczerze, zgodnie ze swoją wiedzą. Jeśli głęboko w coś wierzy, to udzieli takiej właśnie informacji. Po udzieleniu odpowiedzi na ostatnie pytanie osoba wychodzi z transu.',1,'','Siła Woli');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     9,'Jeździectwo','Bohater potrafi jeździć konno lub na innych wierzchowcach. Zwykłe jeżdżenie w normalnych warunkach nie wymaga wykonywania testu umiejętności.
Jednakże może on być konieczny w przypadku jazdy galopem, wyścigu, podczas jazdy w trudnym terenie, wskakiwaniu na konia w biegu, itp.',NULL,'wołtyżerka','Zręczność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     10,'Język tajemny','Dzięki tej umiejętności Bohater może rzucać zaklęcia.
Znajomość języka tajemnego jest konieczna przy używaniu magicznych formuł. W odróżnieniu od innych języków, język tajemny nie jest używany w codziennych rozmowach, a wyłącznic do manipulowania mocą magiczną. Wszystkie magiczne pergaminy i księgi zapisane są w określonym języku
tajemnym. Istnieje wiele języków tajemnych. Najczęściej
używane to: demoniczny. magiczny {znany wśród uczonych w Imperium pod nazwą Lingua Practtantia) i tajemny clfi.',1,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     11,'Kuglarstwo (różne)','Kuglarstwo wykorzystywane jest do zabawiania publiczności.
Podobnie jak w przypadku nauki i wiedzy, nazwa kuglarstwo określa kategorię oddzielnych umiejętności. Najczęściej spotykanymi rodzajami kuglarstwa są: akrobatyka, aktorstwo, błaznowanie, gawędziarstwo, komedianctwo. mimika, muzykalność, połykanie ognia, śpiew, taniec, wróżenie z dłoni, żonglerka.',1,'czlowick-guma, naśladowca','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     12,'Leczenie','Dzięki tej umiejętności Bohater może zapewnić opiekę medyczną rannej osobie. Udany test leczenia przywraca IklO punktów Żywotności w przypadku osoby lekko rannej lub I punkt Żywotności w przypadku osoby ciężko rannej. Ranna osoba może być leczona tylko raz podczas sytuacji krytycznej (bitwa, zasadzka, pułapka, upadek, itp.). która spowodowała utratę punktów Żywotności, lub zaraz po niej. Test leczenia można ponowić następnego dnia, jak również każdego kolejnego dnia. Szczegółowe zasady leczenia ran znajdziesz
w Rozdziale V I: Walka, obrażenia i ruch',1,'chirurgia','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     13,'Mocna głowa','Ta umiejętność zwiększa odporność Bohatera na alkohol.
Doświadczeni poszukiwacze przygód potrafią sporo wypić i jednocześnie zachować względną trzeźwość. Test umiejętności wykonuje się po każdej porcji wypitego alkoholu. Więcej informacji o napojach alkoholowych i skutkach ich spożycia znajdziesz w Rozdziale V:
Ekwipunek.',NULL,'','Odporność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     14,'Nauka (różne)','Ta umiejętność wykorzystywana jest do zapamiętywania ważniejszych informacji i liczb, jak też (gdy Bohater posiada materiały pomocnicze i odpowiednie zasoby) do badań naukowych. Wymaga intensywnych studiów, lecz, zapewnia znacznie szerszą i jednocześnie bardziej szczegółową znajomość problemu niż w przypadku wiedzy ogólnej.
Nauka nie jest pojedynczą umiejętnością, lecz kategorią obejmującą różne, odrębnie traktowane umiejętności. Każda z nich musi zostać wykupiona oddzielnie. Musisz wydać 100 PD za każdą opanowaną naukę (w nawiasie wpisujesz nazwę wyuczonej specjalności). Na przykład umiejętność nauka (teologia) jest odrębną umiejętnością niż nauka (historia).
Najczęściej spotykane dziedziny nauki to: alchemia, astronomia, demonologia, filozofia, gencalogia/heraldyka. historia, inżynieria, magia, matematyka, nckromancja, prawo, runy, strategia/taktyka, sztuka oraz teologia.',1,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     15,'Nawigacja','Umiejętność ta wykorzystywana jest do orientowania się na lądzie i na wodzie. W zależności od wiedzy i możliwości, Bohater może nawigować według mapy albo gwiazd lub posługując się wrodzonym wyczuciem kierunku. Dzięki tej umiejętności może również ocenić długość podróży, biorąc pod uwagę topografię okolicy, porę roku i pogodę.
W normalnych warunkach, utrzymanie stałego kursu wymaga jednego udanego testu umiejętności dziennie.
W wyjątkowych sytuacjach Mistrz. Gry może zażądać dodatkowych testów umiejętności.',1,'geniusz arytmetyczny, wyczucie kierunku.','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     16,'Opieka nad zwierzętami','Umiejętność ta wykorzystywana jest podczas doglądania zwierząt domowych i hodowlanych (konie, woły, Świnic, psy, itd.). Codzienne czynności i karmienie zwierząt nie wymagają testu umiejętności. Może być jednak potrzebny przy próbie wykrycia objawów choroby lub zastosowaniu specjalnych zabiegów (na przykład zaplatanie grzywy, czesanie, przygotowanie konia do parady wojskowej, itp.).',NULL,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     17,'Oswajanie','Wykorzystanie tej umiejętności umożliwia oswajanie zwierząt. Zwierzęta domowe i hodowlane zawsze zachowują się przyjaźnie wobec Bohatera, który posiada tę umiejętność.
Zwierzęta dzikie lub tresowane (na przykład psy gończe lub bojowe) mogą dać się oswoić przy udanym teście umiejętności. M istrz Gry'' może przydzielić modyfikatory przy próbie oswajania zwierząt wyjątkowo agresywnych lub wyjątkowo wiernych innej osobie. Umiejętność oswajanie nic działa na potwory',1,'','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     18,'Otwieranie zamków','Bohater potrafi otwierać wszelkiego rodzaju zamki i kłódki.
Zazwyczaj do otwarcia zamka wystarczy jeden udany test umiejętności, ale przy próbach otworzenia szczególnie skomplikowanego mechanizmu Mistrz Gry może zażądać dodatkowych testów umiejętności.',1,'','Zręczność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     19,'Plotkowanie','Wykorzystanie tej umiejętności pozwala na zbieranie informacji w czasie zwykłej rozmowy. Obejmuje wymianę najświeższych nowin, plotek o ważnych osobach oraz ogólnych informacji o wydarzeniach w okolicy.',NULL,'etykieta, łotrzyk.','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     20,'Pływanie','Bohater umie pływać oraz nurkować. Pływanie w spokojnej wodzie nic wymaga testu umiejętności. Test może być potrzebny przy próbie nurkowania, pływania w wartkim lub zdradliwym nurcie oraz podczas próby przepłynięcia dłuższego dystansu. W czasie pływania Szybkość Bohatera spada o połowę (zaokrąglane w górę).',NULL,'','Krzepa');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     21,'Powożenie','Bohater potrafi kierować wozem, powozem, a nawet rydwanem. Powożenie w normalnych warunkach nie wymaga testu umiejętności. Test może być potrzebny w przypadku jazdy w trudnym terenie, z dużą prędkością lub przy wykonywaniu niebezpiecznych manewrów.',NULL,'','Krzepa');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     22,'Przekonywanie','Ta umiejętność pozwala Bohaterowi wpływać na zachowanie innych osób. Może przekonywująco kłamać, blcfować, a nawet skutecznie żebrać. Przekonywanie wykorzystuje się też podczas prób uwodzenia. W przypadku zastosowania tej umiejętności w celu nakłonienia kogoś do zrobienia czegoś niezwykłego lub niebezpiecznego. Mistrz Gry może pozwolić nakłanianej postaci na test Siły Woli. Bohater może próbować przekonać kilka osób (jedna osoba za każde 10 punktów’ jego Oglądy), pod warunkiem że wszystkie te osoby rozumieją język, którym posługuje się BG.',NULL,'etykieta, intrygant, krasomówstwo, łotrzyk, przemawianie.','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     23,'Przeszukiwanie','Ta umiejętność jest wykorzystywana przy przeszukiwaniu obszaru lub pomieszczenia, w nadziei znalezienia wskazówek, ukrytych przejść, skarbów lub pułapek.
Dokładne przeszukanie pomieszczenia lub niewielkiego obszaru wymaga jednego udanego testu umiejętności.',NULL,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     24,'Rzemiosło','Bohater jest fachowcem w jednej z dziedzin rzemiosła. Ta umiejętność obejmuje także tc dziedziny, które formalnie nie są określone jako rzemiosło, ale wymagają posiadania wyuczonej wiedzy i odpowiednich narzędzi. Każda umiejętność rzemiosło dotyczy odrębnej dziedziny. W nawiasie podano cechę, która jest powiązana z daną umiejętnością. Najczęściej spotykanymi dziedzinami rzemiosła są: aptekarstwo (Int), bednarstwo (S). garbarstwo (S), gotowanie (Int). górnictwo (S), handel (Ogd), jubilerstwo (Zr), kaligrafia (Zr), kamieniarstwo (Zr), kartografia (Zr), kowalstwo (S), krawiectwo (Zr), młynarstwo (S), piwowarstwo (Int), płatnerstwo (S). rusznikarstwo (Zr), tynurstwo (Zr), stolarstwo (Zr), szkutnictwo (Int), szewstwo (Zr), sztuka (Zr), świccarstwo (Zr), uprawa ziemi (S), wyrób łuków (Zr), zielarstwo (Int) oraz złotnictwo (Zr).',1,'krasnoludzki fach, talent artystyczny.','różnie');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     25,'Sekretne znaki (różne)','Bohater potrafi odczytywać lub zapisywać zaszyfrowane wiadomości. Na obszarze Imperium stosuje się wiele systemów znaków. Sekretne znaki są zazwyczaj prostymi komunikatami używanymi głównie w celu ostrzeżenia, oznakowania obiektu, wskazania szlaku lub miejsca o szczególnym znaczeniu. Odczytanie lub zapisanie krótkiej, prostej wiadomości nie wymaga testu umiejętności.
W przypadku bardziej skomplikowanych zapisów lub gdy fragmenty znaku są podniszczone albo zatarte. M istrz Gry może nakazać wykonanie testu umiejętności z odpowiednimi modyfikatorami trudności. Najczęściej wykorzystywane są znaki: łowców, rycerzy zakonnych, złodziei i zwiadowców.',1,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     26,'Sekretny język (różne)','Znajomość sekretnego języka pozwala na potajemne porozumiewanie się z przedstawicielami tej samej profesji lub grupy społecznej. Sekretne języki przypominają raczej uproszczony szyfr, a nic powszechnie używane formy porozumiewania się. Wykorzystując znaki, mowę ciała i słowa kodowe wplatane w zwykłą wypowiedź. Bohater może przekazać dodatkowe znaczenie wypowiadanych słów lub większą ilość informacji w krótkim czasie.
W normalnych warunkach, gdy wszyscy rozmawiający znają dany sekretny język, test umiejętności nic jest potrzebny, aczkolwiek może być wymagany w niesprzyjających warunkach (na przykład na głośnej ulicy lub w czasie bitwy).
Najczęściej używane sekretne języki to: bitewny, łowców i złodziejski.',1,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     27,'Skradanie się','Umiejętność ta umożliwia Bohaterowi ciche poruszanie się w prawie każdym terenie. Skradając się, Bohater może wykonywać najwyżej jedną akcję „nich" w randzie. Test skradania się jest często wykonywany w przeciwstawnym teście umiejętności przeciwko spostrzegawczości przeciwnika.',NULL,'grotołaz, ulicznik, wędrowiec','Zręczność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     28,'Splatanie magii','Wykorzystanie tej umiejętności ułatwia Bohaterowi kontrolowanie Wiatrów Magii. Każde rzucenie zaklęcia wymaga manipulacji Wiatrami Magii, jednak splatanie magii wykorzystuje się wtedy, gdy wymagana jest większa kontrola nad czarem lub jego precyzyjne przygotowanie. Szczegółowe zasady dotyczące rzucania zaklęć i umiejętności splatania
magii znajdziesz w Rozdziale V II: Magia.',1,'zmysł magii','Siła Woli');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     29,'Spostrzegawczość','Bohater Gracza, który posiada tę umiejętność, dokładniej obserwuje otoczenie, często zauważając szczegóły przeoczone przez innych. Dzięki temu ma większe szanse na zauważenie pułapki, zapadni lub ukntego przejścia.
Spostrzegawczość jest używana głównie do ustalania tego co Bohater widzi, choć obejmuje także pozostałe zmysły, Może więc być użyta do określania doznań smakowych, zapachowych, słuchowych i dotykowych. Spostrzegawczość bywa często stosowana w przeciwstawnych testach umiejętności, szczególnie przeciwko takim umiejętnościom
jak charakteryzacja, skradanie się i ukrywanie się. Udany
test umiejętności pozwala Bohaterowi na określenie liczebności, odległości, wielkości obserwowanego obiektu, itp. Nieudany test może oznaczać uzyskanie niedokładnych informacji.',NULL,'bystry wzrok, czuły słuch, geniusz arytmetyczny','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     30,'Sztuka przetrwania','Umiejętność ta może zapewnić przeżycie w dziczy. Obejmuje znajomość technik łowienia ryb, polowania, oprawiania zwierzyny, rozpalania ognia, znajdowania pożywienia, konstruowania szałasów, itp.',NULL,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     31,'Siedzenie','Wykorzystując tę umiejętność, bohater może podążać za kimś, samemu pozostając niezauważonym. Test śledzenia jest często wykonywany w przeciwstawnym teście umiejętności przeciwko spostrzegawczości przeciwnika.',1,'','Zręczność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     32,'Targowanic','Umiejętność ta umożliwia negocjowanie cen towarów i usług. W przypadku towarów codziennego użytku wystarczy zwykły test umiejętności. Jeśli Bohater targuje się o cenny przedmiot (na przykład próbuje ustalić koszt wyjątkowo cennego rękopisu), Mistrz Gry może zarządzić przeciwstawny test targowania (z ewentualnymi modyfikatorami trudności)',NULL,'żyłka handlowa','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     33,'Torturowanie','Dzięki zastosowaniu rozmaitych działań i środków przymusu Bohater potrafi wydobyć interesujące go informacje od osoby niechętnej do współpracy. Umiejętność obejmuje zarówno psychiczne znęcanie się, jak i fizyczne tortury. Ofiara może opierać się torturom, wykonując test Siły Woli.',1,'groźny','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     34,'Tresura','Bohater potrafi uczyć zwierzęta wykonywania różnych sztuczek i słuchania prostych poleceń. Zwykle tresurze poddajc się psy, konie i sokoły, choć M istrz G ry może pozwolić na tresowanie bardziej niezwykłych zwierząt.
Wyuczenie zwierzęcia zajmuje sporo czasu. Test umiejętności należy wykonywać raz na tydzień tresury.
Nauczenie prostej sztuczki wymaga pojedynczego, udanego testu, średnio trudna sztuczka wymaga trzech udanych testów umiejętności, natomiast bardzo trudna - dziesięciu udanych testów umiejętności.',1,'','Ogłada');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     35,'Tropienie','Bohater potrafi wyszukiwać ślady zwierząt, a także ludzi i innych stworzeń. Podążanie wyraźnym tropem nic wymaga testu umiejętności i nic spowalnia tempa poruszania się.
Test umiejętności może być jednak potrzebny w trudnych warunkach terenu lub pogody. Odpowiedni poziom skuteczności może dostarczyć dodatkowych informacji (o liczebności grupy, odległości od tropionego stworzenia, a nawet jego cechach osobniczych).',1,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     36,'Ukrywanie się','Wykorzystanie tej umiejętności umożliwia Bohaterowi ukrywanie się w niemal dowolnym terenie, pod warunkiem, że istnieje realna szansa schowania się za jakimś obiektem (mur, drzewo, budynek, itp.). Przy próbie ukrycia się na otwartej, pustej przestrzeni (na przykład na środku ulicy) test umiejętności automatycznie jest nieudany. Ukrywanie się bywa często wykorzystywane przeciwko testowi
spostrzegawczości przeciwnika.',NULL,'grotołaz, ulicznik, wędrowiec','Zręczność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     37,'Unik','Wykorzystanie tej umiejętności umożliwia Bohaterowi uniknięcie ataku podczas walki wręcz. Unik można stosować najwyżej raz na rundę. Szczegółowe zasady unikania ciosów
znajdziesz w Rozdziale V I: Walka, obrażenia i ruch.',1,'','Zręczność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     38,'Warzenie trucizn','Bohater potrafi przyrządzać rozmaite trucizny pochodzenia zwierzęcego lub roślinnego, a także trucizny uzyskiwane alchemicznie. Szczegółowy opis trucizn i efektów ich działania znajdziesz w Rozdziale V: Ekwipunek.',1,'','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     39,'Wiedza (różne)','Umiejętność ta zapewnia wiedzę o zwyczajach, strukturze władzy, najważniejszych dostojnikach, obyczajach ludowych oraz przesądach mieszkańców danej krainy, członków danej grupy społecznej lub przedstawicieli danej rasy’. Wiedza nic jest równoznaczna ze studiami naukowymi (to oddaje umiejętność nauka), lecz zapewnia jedynie podstawowe informacje, jakie Bohater zdobył w czasie podróży po święcie. Podobnie jak w przypadku umiejętności nauka, w iedza to szersza kategoria obejmująca różne, oddzielnie zdobywane konkretne umiejętności. Najczęściej wiedza dotyczy: Bretonii, Estalii, Imperium, Jałowej Krainy, Ki$leva, Księstw Granicznych, Norski, Tilci oraz elfów, krasnoludów, niziolków i ogrów.',1,'obieżyświat','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     40,'Wioślarstwo','Bohater potrafi sterować tratwami, barkami i innymi łodziami wiosłowymi. Utrzymanie kursu w normalnych warunkach i proste manewry nic wymagają testu umiejętności. M istrz G ry może uznać za stosowne wykonanie testu umiejętności w przypadku kiepskiej pogody, wysokiej fali, pokonywania progów rzecznych lub omijania mielizn.',NULL,'','Krzepa');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     41,'Wspinaczka','Twój Bohater potrafi wspinać się na drzewa, mury. skalne ściany i inne pionowe przeszkody. W normalnych warunkach test umiejętności wykonuje się raz na rundę.
Wspinanie się w czasie walki wymaga poświęcenia akcji podwójnej. Udany test oznacza, że Bohater wspiął się na wysokość równą połowuc jego Szybkości (zaokrąglane w górę), mierzoną w metrach.',NULL,'','Krzepa');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     42,'Wycena','Bohater potrafi szacować wartość rzeczy codziennego użytku, jak również przedmiotów wartościowych, takich jak biżuteria, klejnoty i dzieła sztuki. Udany test umiejętności pozwala określić rynkową wartość przedmiotu. Ponieważ nieudany test umiejętności może spowodować błędne oszacowanie wartości przedmiotu, M istrz G ry powinien wykonać rzut w tajemnicy i zależnie od wyniku poinformować gracza o ustalonej w ten sposób wartości przedmiotu.',NULL,'talent anystyczny, żyłka handlowa.','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     43,'Wykrywanie magii','Umiejętność ta umożliwia Bohaterowi wykrywanie subtelnych zawirowań, jakie towarzyszą magicznej aurze.
Czarodzieje opisują to jako szósty, siódmy i ósmy zmysł człowieka. Wśród chłopstwa to zjawisko znane jest pod nazwą .wiedżmi wzrok". Udany test umiejętności pozwala określić, czy przedmiot, postać lub obszar pozostajc pod wpływem czaru. Wykorzystując tę umiejętność, czarodziej może ustalić silę W iatrów Magii w najbliższej okolicy.
Dodatkowe informacje na ten temat znajdziesz
w Rozdziale V II: Magia',1,'zmysł magii','Siła Woli');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     44,'Zastawianie pułapek','Bohater potrafi konstruować różnego rodzaju pułapki na zwierzęta. W Imperium używa się pułapek unieruchamiających, jak też uśmiercających złapane zwierzę. Za każdą założoną pułapkę wykonuje się jeden test umiejętności na dzień. Udany test oznacza, że w pułapkę złapało się zwierzę.',1,'','Zręczność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     45,'Zastraszanie','Dzięki tej umiejętności Bohater może zastraszać lub zmuszać do uległości inne osoby. O fiary, które nic chcą ugiąć się przed groźbami, mogą wykonać test Siły Woli.
Reakcja postaci zależy całkowicie od decyzji Mistrza Gry, który bierze pod uwagę jej osobowość oraz w ynik testu zastraszania. W niektórych sytuacjach (szantaż, itp.), M istrz Gry może uznać, że bardziej odpowiednią cechą do testu zastraszania może być Ogłada.',NULL,'groźny','Krzepa');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     46,'Znajomość języka','Ta umiejętność umożliwia Bohaterowi porozumiewanie się w obcym języku. Większość języków Starego Świata wywodzi się ze wspólnego starożytnego narzecza, choć w ciągu wiciu wieków różnice między poszczególnymi dialektami doprowadziły do powstania odrębnych języków. W normalnych warunkach, gdy wszyscy rozmawiający znają dany język, test umiejętności nic jest potrzebny. Test umiejętności może być potrzebny w przypadku prób naśladowania regionalnych akcentów lub gdy Bohater Gracza próbuje przekonać słuchających, że język obcy jest ojczystym jego językiem. Najczęściej używanymi językami są: bretoński (Brctonia), eltharin (e lfi). estalijski (Estalia), khazalid (krasnołudzki), kislcvski (Ki$lev), norski (N orska), tileański (Tiłca) oraz Reikspiel czyli staroświatowy (Imperium ) i nieco podobny do niego język niziołków. Uczeni posługują się także językiem klasycznym, choć obecnie występuje on głównie w formie pisanej. M niej cywilizowane rasy posługują się językiem goblińskim (orki, gobliny i hobgobliny), narzeczeni grumbarth (ogry) oraz mroczną mową (zw ier/oludzie i inne istoty Chaosu).',1,'naśladowca, obieżyświat, poliglota.','Inteligencja');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     47,'Zwinne palce','Dzięki tej użytecznej umiejętności Bohater potrafi ukryć w dłoni małe przedmioty lub wykonywać sztuczki z kartami i monetami. Zw inne palce przydają się również przy ukradkowym sięganiu do cudzych sakiewek. Test zwinnych palców jest często wykonywany w przeciwstawnym teście umiejętności przeciwko spostrzegawczości przeciwnika',1,'','Zręczność');
INSERT INTO PUBLIC.SKILL (ID,NAME,DESCRIPTION,ISADVANCED,RELATEDTALENTSSTRING,CHARACTERISTIC) VALUES (
                                                                                                     48,'Żeglarstwo','Dzięki tej umiejętności Bohater potrafi sterować statkami żaglowymi. Dodatkowo Bohater dysponuje wiedzą o budowie okrętów, różnych rodzajach żagli, a także umiejętnością przewidywania pogody na morzu.
Żeglowanie po spokojnych wodach nie wymaga testu umiejętności. Trudne warunki pogodowe, wysokie falc łub wykonywanie manewrów w czasie bitwy mogą wymagać testu umiejętności o odpowiednim stopniu trudności.',1,'','Zręczność');
